name: python3r4
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.8.*
  - pip:
    - causaldag
    - cdt==0.6.0
    - graphical_models
    - conditional_independence
    - matplotlib==3.5.*
    - networkx==2.8.*
    - numpy
    - argparse
    - pandas==1.*
    - scikit-learn==1.*
    - scipy==1.9.*
    - rpy2==3.5.*
