install.packages("tictoc", repos = "http://cran.us.r-project.org")
install.packages("BiocManager", repos="http://cran.us.r-project.org")
library(BiocManager)
BiocManager::install(c("graph", "RBGL", "Rgraph"), lib="/homes/shahashka/gies_libs")
install.packages("pcalg", repos = "http://cran.us.r-project.org")
